#!/usr/bin/env bash
# Generate a production-ready .env from .env.example with random secrets.
# Usage: ./scripts/bootstrap-env.sh [output-file]
set -euo pipefail

OUT="${1:-.env}"
EXAMPLE="$(dirname "$0")/../.env.example"

if [[ -f "$OUT" ]]; then
    echo "Refusing to overwrite existing $OUT" >&2
    exit 1
fi

POSTGRES_USER="orvixa_prod"
POSTGRES_PASSWORD="$(openssl rand -hex 24)"
POSTGRES_DB="orvixa"
REDIS_PASSWORD="$(openssl rand -hex 24)"
API_KEY="$(openssl rand -hex 32)"

cp "$EXAMPLE" "$OUT"

sed -i.bak \
    -e "s|^APP_ENV=.*|APP_ENV=production|" \
    -e "s|^API_KEY=.*|API_KEY=${API_KEY}|" \
    -e "s|^POSTGRES_DSN=.*|POSTGRES_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}|" \
    -e "s|^REDIS_URL=.*|REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0|" \
    "$OUT"
rm -f "${OUT}.bak"

{
    echo ""
    echo "# --- generated by bootstrap-env.sh, required by docker-compose.prod.yml ---"
    echo "POSTGRES_USER=${POSTGRES_USER}"
    echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    echo "POSTGRES_DB=${POSTGRES_DB}"
    echo "REDIS_PASSWORD=${REDIS_PASSWORD}"
} >> "$OUT"

echo "Wrote $OUT with generated secrets."
echo "Edit CORS_ORIGINS in $OUT to your real frontend domain before deploying."
